version: '3.3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379
    networks:
      - default-notwork
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - default-notwork
  rbac:
    image: limingxinleo/rbac-api:latest
    ports:
      - 9502:9502
    networks:
      - default-notwork
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
    depends_on:
      - redis
      - mysql
networks:
  default-notwork:
